<a href="https://colab.research.google.com/github/Jessidisabi/Atividade-solo-generation-passe-1/blob/main/Atividade_solo_generation_passe_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# -------DICAS---------

url = 'https://api.open-meteo.com/v1/forecast'

# parametros utilizados
parametros = {
    'latitude' : lat,
    'longitude' : lon,
    'daily' : ['temperature_2m_max','precipitation_sum'],
    'timezone' : 'auto',
    'past_days' : quantos_dias
}

# como chamar os dados
dados_diarios = dados['daily']

# criar a base de dados
import pandas as pd
df_dados_clima = pd.DataFrame(dados_diarios)

# salvar isso no csv
df_dados_clima.to_csv('relatorio_prof_luiz.csv', index=False)

In [ ]:
# Etapa 1: Preparar o Terreno (Inputs e Parâmetros)
# conectar a api e colocar parametros

# Etapa 2: Coleta de Dados e Verificação
# usar o get
# if do status_code
# salvar no json
# criar o dataframe com o pandas
# se quiser display(dataframe)

# Etapa 3: Salvar os Dados (O Arquivo CSV)
# salva o arquivo

# EXTRA - mostrar no padrao dos estados unidos
# (temperatura * 1.8) + 32

In [1]:
import requests
import pandas as pd

In [3]:
lat = -24.00
lon = -46.41

url = 'https://api.open-meteo.com/v1/forecast'

parametros = {
    'latitude': lat,
    'longitude': lon,
    'daily': ['temperature_2m_max', 'precipitation_sum'],
    'timezone': 'auto',
    'past_days': 7
}

In [4]:
resposta = requests.get(url, params=parametros)

print(resposta.status_code)

200

In [5]:
dados = resposta.json()

In [6]:
dados_diarios = dados['daily']

In [7]:
df_dados_clima = pd.DataFrame(dados_diarios)

df_dados_clima

          time  temperature_2m_max  precipitation_sum
0   2026-04-08                28.1                0.0
1   2026-04-09                23.7                0.7
2   2026-04-10                21.9                0.6
3   2026-04-11                23.2                0.0
4   2026-04-12                24.3                0.0
5   2026-04-13                25.7                0.1
6   2026-04-14                24.6                0.0
7   2026-04-15                24.7                0.0
8   2026-04-16                25.4                0.0
9   2026-04-17                28.5                0.0
10  2026-04-18                27.8                4.3
11  2026-04-19                23.2                0.0
12  2026-04-20                25.1                0.0
13  2026-04-21                26.1                0.0

In [8]:
df_dados_clima.to_csv('relatorio_prof_luiz.csv', index=False)

In [9]:
df_dados_clima['temp_fahrenheit'] = (df_dados_clima['temperature_2m_max'] * 1.8) + 32

df_dados_clima

          time  temperature_2m_max  precipitation_sum  temp_fahrenheit
0   2026-04-08                28.1                0.0            82.58
1   2026-04-09                23.7                0.7            74.66
2   2026-04-10                21.9                0.6            71.42
3   2026-04-11                23.2                0.0            73.76
4   2026-04-12                24.3                0.0            75.74
5   2026-04-13                25.7                0.1            78.26
6   2026-04-14                24.6                0.0            76.28
7   2026-04-15                24.7                0.0            76.46
8   2026-04-16                25.4                0.0            77.72
9   2026-04-17                28.5                0.0            83.30
10  2026-04-18                27.8                4.3            82.04
11  2026-04-19                23.2                0.0            73.76
12  2026-04-20                25.1                0.0            77.18
13  2026-04-21                26.1                0.0            78.98